### ISSUE TITLE
Indicator not position well on Catalina

### ISSUE THREAD

**Issue by BoWuGit** [pqrs-org/ShowyEdge#14]
Like the following picture indicates, it doesn't position at left top corner. After adjusting width or height of the indicator, it positions well, but after a while, not knowing how, it moved there again. Thanks for your attention.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/6310246/67918779-b8983000-fbd8-11e9-94e2-1facc05b9776.png">

**Comment by tekezo** [comment]
I cannot reproduce this issue.

Did you enable custom frame?
https://showyedge.pqrs.org/docs/configuration/indicator-size-configuration/#advanced

**Comment by BoWuGit** [comment]
Yes, I have used it. Still not knowing how, it works well recently, would it be system upgrade or something else, I don't know. Anyway, thanks.
