### ISSUE TITLE
stack order

### ISSUE THREAD

**Issue by samxyzabc** [pqrs-org/ShowyEdge#15]
Dear dev,

I am writing to ask if there's a way to put the indicator bar under the very bottom of all other windows, not on top instead?

Thanks!

**Comment by tekezo** [comment]
I released ShowyEdge-3.7.0 which contains `Show indicator behind app windows` option.
Try it!
https://showyedge.pqrs.org/docs/configuration/indicator-options/

**Comment by samxyzabc** [comment]
That's really great! The app is much convenient for me.
![image](https://user-images.githubusercontent.com/8305492/71308365-abf4c300-2436-11ea-9946-90de94780a27.png)
