### ISSUE TITLE
希望能支持 Rime -- 鼠须管/或其他中文输入法的输入法内中英文切换状态显示

### ISSUE THREAD

**Issue by Justsoos** [pqrs-org/ShowyEdge#16]
安装 鼠须管 和 ShowyEdge 配合有逻辑矛盾，即 shwoedge 并不能显示鼠须管内中英文切换，实际上，rime 本身自动化在不同程序间切换，并替代系统英文输入法是简单又好用的，但为了配合 showyedge，强行出现了这样的用法：
https://pbeta.me/macos-from-zero-3/
 - 关闭鼠须管的英文输入
 - 把中英文输入法之间切换行为独特强调出来
 - 这样才能够使用ShowyEdge的功能
如题，希望能有这样的功能

https://github.com/rime/squirrel/issues/146

**Comment by yetangye** [comment]
我在使用搜狗拼音输入法，期望还能区别出搜狗拼音的中文状态和英文状态，谢谢。
目前只能给搜狗输入法整体设定一个色条，无法给搜狗拼音的中文状态和英文状态分别设定色条。

**Comment by GanZhiXiong** [comment]
@Justsoos @yetangye
我用的搜狗输入法，我也想让其区分下搜狗输入法下按 shift 切换中英文的状态。
请这个问题你们有解决办法吗？
