### ISSUE TITLE
Show indicator at the position of cursor when application switched 

### ISSUE THREAD

**Issue by cocobear** [pqrs-org/ShowyEdge#17]
Like this:
<img width="565" alt="Screen Shot 2020-01-01 at 12 58 20 PM" src="https://user-images.githubusercontent.com/181942/71638299-16a7c900-2c97-11ea-92a1-cf9f0bac1048.png">

When we switch application, and input form get focus, we want to know which input source is using.
I think it is possible and comfortable.

**Comment by samxyzabc** [comment]
yes, if this feature could be implemented, it would be terrific.

**Comment by tekezo** [comment]
There are no way to get the caret position on macOS without the editor help as far as my understand, unfortunately.

**Comment by cocobear** [comment]
I didn't know mac dev , can you check this :
https://stackoverflow.com/questions/25610607/how-to-find-the-blinking-cursor-location-of-any-active-application
