### ISSUE TITLE
"Hide Indicator when full screen" not working

### ISSUE THREAD

**Issue by sunqiuming526** [pqrs-org/ShowyEdge#20]
I'm using MacOS 10.15 and "Hide Indicator when full screen" option is on. But the indicator is still shown under full screen mode. 

![image](https://user-images.githubusercontent.com/21358630/85428426-0d0a6a00-b532-11ea-9da2-0227d644bcdc.png)

**Comment by tekezo** [comment]
Thank you for feedback!

I believe this issue was fixed the latest release v4.0.0.

Please confirm v4.0.0.
https://showyedge.pqrs.org/docs/releasenotes/

**Comment by sunqiuming526** [comment]
> Thank you for feedback!
> 
> I believe this issue was fixed the latest release v4.0.0.
> 
> Please confirm v4.0.0.
> https://showyedge.pqrs.org/docs/releasenotes/

Awesome! Thanks so much🎉
