### ISSUE TITLE
ability to exclude specific apps in fullscreen mode

### ISSUE THREAD

**Issue by deepsweet** [pqrs-org/ShowyEdge#8]
hi.

I know you are working hard on Karabiner-Elements now, but maybe you'll have some time to spend here :)

I like ShowyEdge and have been using it for the last month, and I realized that there is one feature I really miss: automatically disable ShowyEdge while watching movies fullscreen in VLC or iTunes. something like a specified list of apps with the following behaviour: current foreground app is in the list and it's in fullscreen mode? ok, ShowyEdge will hide itself.

thanks!

**Comment by wxmtech** [comment]
Good idea, when trying to watch a movie, sometimes it feels wired and then I have to switch it back. If the app is smart enough to differentiate when app window has a text input area, otherwise, a simple whitelist still be useful.

**Comment by zhanggang807** [comment]
+1
